version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: messaging_db
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"   # host:container
    volumes:
      - mysql_data:/var/lib/mysql   # ✅ persistent storage

  web:
    build: .
    container_name: messaging_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  mysql_data:   # ✅ define named volume

# python3 manage.py runserver
# environment
# ["MYSQL_USER", "MYSQL_DB", "MYSQL_PASSWORD"]
